// 'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from  "./provider";
import { Suspense } from "react";
import Loading from "./loading";
// import { Provider } from 'react-redux';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chatapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Provider >
    
        <Suspense fallback={<Loading />}>
    <body >
   
        {children}
      {/* <div className={inter.className}>{children}</div> */}
      </body>
        </Suspense>
    {/* </Provider> */}
    </Provider>
    </html>
  );
}
